// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tujvjvlxgsauhybvttbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1anZqdmx4Z3NhdWh5YnZ0dGJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNzM4NDMsImV4cCI6MjA2MDg0OTg0M30.oMVHE7U4wuVrikzzseiCz6zcRQHPlCmlebm_K_rPMdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);